listening_address = "0.0.0.0:80"
client_max_connections = 1024
worker_threads = 256
log_directory = "log"
log_name_prefix = "ppaass-proxy.log"
max_log_level = "ERROR"
user_repo_directory = "resources/proxy/user"
user_repo_refresh_interval = 10
user_info_file_name = "user_info.toml"
user_info_public_key_file_name = "AgentPublicKey.pem"
user_info_private_key_file_name = "ProxyPrivateKey.pem"
destination_connect_timeout = 20
#forward.username = "user1"
#forward.user_repo_directory = "resources/proxy/forward_user"
#forward.user_repo_refresh_interval = 10
#forward.user_info_file_name = "user_info.toml"
#forward.user_info_public_key_file_name = "ProxyPublicKey.pem"
#forward.user_info_private_key_file_name = "AgentPrivateKey.pem"
#forward.proxy_connect_timeout = 20