[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { workspace = true, features = ["v4"] }
rand = { workspace = true }
thiserror = { workspace = true }
bincode = { workspace = true, features = ["serde"] }